### ISSUE TITLE
Snapshots do not work (redesign branch)

### ISSUE THREAD

**Issue by ArkaneMoose** [ArkaneMoose/BotBot#11]
Snapshots do not currently work in the "redesign" branch.

**Comment by jedevc** [comment]
The snapshots do work in this. However - there are still problems.

**Comment by ArkaneMoose** [comment]
Are there still issues with snapshots?

**Comment by ArkaneMoose** [comment]
With d3465d5, I think it is safe to close this issue. @jedevc, any objections?

**Comment by jedevc** [comment]
Nope.
