### ISSUE TITLE
!ping overreacting

### ISSUE THREAD

**Issue by CylonicRaider** [ArkaneMoose/BotBot#16]
`!ping` with an @-mention triggers reponses from bots that are not mentioned.

**Comment by jedevc** [comment]
Is this intended to be a feature for all bots? Because most of mine definitely do not respond to bot-specific !pings.

**Comment by CylonicRaider** [comment]
That's a BotBot bug, yours should be independent from it, @jedevc.

**Comment by jedevc** [comment]
Ah yes. This is made clearer from the standards discussion yesterday. Sorry.

**Comment by ArkaneMoose** [comment]
To be honest, I did not think that `!ping` with an @-mention was supposed to have specific behavior. However, I've fixed this in commit c947225.
