### ISSUE TITLE
Revamp snapshot system

### ISSUE THREAD

**Issue by ArkaneMoose** [ArkaneMoose/BotBot#20]
Here's what I'm thinking:
The snapshot system should be incremental.

I think the system should be something like this:
1. Whenever someone creates a bot, add it to a snapshot file called "autosave".
2. Whenever someone kills a bot, remove it from "autosave".
3. Whenever someone creates a snapshot, copy "autosave" to "MM-dd-yyyy_hhmmss.json".
4. When BotBot starts (e.g. after a crash), it should load from "autosave".

That way, no data is lost on a crash, and everything is easier.

The snapshot system doesn't have to "incremental" per se, but it should autosave in the way I described, i.e. it should write a new autosave file whenever a bot is created or killed.

**Comment by jedevc** [comment]
This sounds good - almost the same idea as I was considering for phlang. Mine was slightly different however - simply store each bot in it's own text file. Then when a backup is created, put all the files in a .tar.gz archive. Then on the bot start, load all the files.

Also, I think that when accounts are added, the bot should only be allowed to be !killalled if you are a botbot admin.

**Comment by ArkaneMoose** [comment]
I think that that's a better way to do it actually; then there's no need for the whole "autosave" JSON file to be loaded at once to add or delete a bot; bots can simply be added and deleted as files on the filesystem.
I think that we don't necessarily need to put the bots in a tarball; snapshots can exist simply as directories on the filesystem. (I don't think tarballing would save a significant amount of disk space.)

Also, I agree with your idea of restricting the `!killall` command to admins, but this would be a separate issue in the future.

**Comment by jedevc** [comment]
Tarballing wouldn't be to save space, but simply a way to keep all the files neatly together.
