### ISSUE TITLE
Compliance with Euphorian bot standards

### ISSUE THREAD

**Issue by ArkaneMoose** [ArkaneMoose/BotBot#21]
BotBot complies with a significant portion of the [bot standards](https://github.com/jedevc/botrulez/blob/master/README.md), but we should aim for full compliance. Of course, bots created with BotBot can choose to ignore the standards (by setting an empty response), but by default, they should all comply.

Here's what we have so far:
(When a missing command is implemented, please check its corresponding box and provide the commit and issue that implements it, if any.)
(This issue should be closed once everything is checked.)
- [x] `!ping`
- [x] `!ping @BotName` (c947225, #16)
- [x] `!help` (d3465d5)
- [x] `!help @BotName`
- [x] `!uptime @BotName` (9419294)
- [x] `!pause @BotName`
- [x] `!restore @BotName`
- [x] `!kill @BotName`
- [x] `!restart @BotBot`

**Comment by ArkaneMoose** [comment]
I'm thinking the `redesign` branch should not be merged until all of this is completed.

**Comment by jedevc** [comment]
Hm. I'd disagree. I think that the redesign branch should be merged as soon as it's fully functional - after all, the purpose of the branch was to sort the code out, which has already mostly been done.

**Comment by jedevc** [comment]
How do you plan to do the !uptime command? It should still be possible to override it. I think maybe using something like (uptime) should replace it with the current uptime of the bot.

**Comment by ArkaneMoose** [comment]
That sounds good. I'll do something like `(uptimeutc)` for a timestamp like `YYYY-mm-dd HH:MM:SS` and `(uptime)` for `1d 3h 3m 7s`.

**Comment by ArkaneMoose** [comment]
Do you think that the time format string should be customizable? Something like `(uptimeutc:%Y-%m-%d %H:%M:%S)`?
