### ISSUE TITLE
!sendbot not implemented (redesign branch)

### ISSUE THREAD

**Issue by ArkaneMoose** [ArkaneMoose/BotBot#22]
Can't believe I just noticed this, but notice [this line](https://github.com/ArkaneMoose/BotBot/blob/redesign/source/botbot.py#L110) where the !sendbot code should be.

**Comment by jedevc** [comment]
Hm. I think bluebird might have mentioned that at some point.

**Comment by ArkaneMoose** [comment]
Fixed as of 0377bb0.
