### ISSUE TITLE
in-line reply

### ISSUE THREAD

**Issue by Garmelon** [ArkaneMoose/BotBot#23]
`!createbot @TestBot test -> normal reply -| inline reply`

would do this:

> [person] test
> 
> > [TestBot] normal reply
> 
> [TestBot] inline reply

**Comment by ArkaneMoose** [comment]
Implemented in 72cfb22, though the syntax is a bit different.

`!createbot @TestBot test -> {normal reply, !inline inline reply}`

does this:

> [person] test
> 
> > [TestBot] normal reply
> 
> [TestBot] inline reply

**Comment by Garmelon** [comment]
Hooray :P
