### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by jedevc** [ArkaneMoose/BotBot#3]
The state of the codebase at the moment is a little bit messy. So, it must be cleaned up a bit.

I suggest that the best way to do this is to try to seperate some objects and functions into seperate modules and to try to make a class that wraps the whole BotBot.

**Comment by ArkaneMoose** [comment]
I've begun by putting the code parser into [a separate file](https://github.com/ArkaneMoose/BotBot/blob/master/source/parser.py).

**Comment by jedevc** [comment]
Ok. That looks good, although I think that some of that code could be modified a little and have a bit of inline commenting.
