### ISSUE TITLE
Weird snapshot file names

### ISSUE THREAD

**Issue by CylonicRaider** [ArkaneMoose/BotBot#31]
It would improbe sortability, increase standards adherence, and follow the principle of least surprize if @BotBot changed to use [ISO 8601](http://xkcd.com/1179) in snapshot filenames, instead of whatever it's currently doing.

**Comment by ArkaneMoose** [comment]
Sorry, I had originally written BotBot to use US-style dates (mm-dd-yyyy). I'm about to push a commit that fixes this.
