### ISSUE TITLE
Botlings do not return after disconnection

### ISSUE THREAD

**Issue by ArkaneMoose** [ArkaneMoose/BotBot#35]
Cause is still unknown. Some botlings remain, fully functional, but the majority do not return.

Things I know:
- Missing botlings are not removed from the ExecGroup
- Missing botlings are not able to listen or respond to the room
- There is no log output, i.e. no errors

Possible causes:
- `quit()` is being called prematurely
- The thread dies prematurely, for some reason

**Comment by ArkaneMoose** [comment]
Actually, I think I may have found [the cause](https://github.com/ArkaneMoose/BotBot/blob/ad0fb2f4557b0830b0540bd7df115e932b176c59/source/botbot.py#L204-L207).

``` python
    def cleanup(self):
        self.bots.quit()

        self.botthread.join()
```

> Possible causes:
> - `quit()` is being called prematurely

If I am correct, `cleanup()` is being called every time BotBot disconnects from the server, so the bots are killed prematurely. @jedevc, can you confirm this?

I'll write a fix for this very soon.

**Comment by jedevc** [comment]
All bots die every time a server disconnect occurs.
